### ISSUE TITLE
Error encountered when try to start the Node server

### ISSUE THREAD

**Issue by BtXin** [eclipse/flux#16]
When I tried to start the node server I encountered an error that:
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! eclipse-flux@0.1.3 start: `node startup-all-in-one.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eclipse-flux@0.1.3 start script 'node startup-all-in-one.js'.
npm ERR! This is most likely a problem with the eclipse-flux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node startup-all-in-one.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls eclipse-flux
npm ERR! There is likely additional logging output above.

Any idea how to solve that?

**Comment by BtXin** [comment]
I updated to the latest version of node but the error still exists

**Comment by martinlippert** [comment]
The code and the version at npm might be a bit outdated and not compatible with the latest node versions anymore, but I haven't tried myself. I would recommend to checkout the repo and start node from the command line using the sources of the project. Nevertheless, you have to use npm to get the dependencies installed, but I am not sure what exactly you did and how that relates to the error mentioned above.

**Comment by martinlippert** [comment]
Also please consider to move those questions to the flux-dev@eclipse.org mailing list for further discussions. I think there are more people on that list than listening to issues on GitHub for this project.

**Comment by BtXin** [comment]
Which version of node did you used?

**Comment by BtXin** [comment]
I figured.... It seemed that I need to start rabbitmq server first then start the node server.

**Comment by martinlippert** [comment]
Glad to hear that you found the solution. Please also send this to the flux-dev@eclipse.org mailing list (as an answer to your own post) so that other people on that list are aware of your solution and don't waste time to find out what was going wrong there.
