### ISSUE TITLE
npm install gives an error on xenial

### ISSUE THREAD

**Issue by rnavagamuwa** [eclipse/flux#21]
Hi,
 I'm trying to run flux inside a docker. During the docker building, following error occurs when `npm install` command executes.

> npm WARN eclipse-flux@0.1.3 license should be a valid SPDX license expression
npm WARN In v8-debug@0.3.5 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.29
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! v8-debug@0.3.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.3.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/flux-master/node.server/npm-debug.log

Please not this error occurs only in **xenial**. When I use **trusty** this works without giving any erros.

**Comment by martinlippert** [comment]
Haven't used this within a docker container yet. Maybe @sunix have come across this?

**Comment by rnavagamuwa** [comment]
@martinlippert i got this solved by adding `--ignore-scripts` flag to `npm install` :smile:

**Comment by martinlippert** [comment]
Glad to hear that you got it working...!!! :-)
